#Generated by Claude

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

fig, axes = plt.subplots(1, 2, figsize=(15, 4))

data_dir = "data"

# Iterate over all subfolders in data/
for map_name in os.listdir(data_dir):
    map_dir = os.path.join(data_dir, map_name)
    if not os.path.isdir(map_dir):
        continue

    birkhoff_path = os.path.join(map_dir, "birkhoff_convergence.csv")
    measure_path  = os.path.join(map_dir, "invariant_measure.csv")

    # Skip if expected files are missing
    if not os.path.exists(birkhoff_path) or not os.path.exists(measure_path):
        print(f"Skipping {map_name} — missing CSV files")
        continue

    fig, axes = plt.subplots(1, 2, figsize=(15, 4))
    fig.suptitle(f"Ergodic properties - {map_name}", fontsize=14)

    # Birkhoff convergence
    df = pd.read_csv(birkhoff_path, header=None, names=["n", "avg"])
    axes[0].plot(df["n"], df["avg"], lw=0.8)
    axes[0].axhline(0.5, color="red", linestyle="--", label="Space average = 0.5")
    axes[0].set_title("Birkhoff Average Convergence")
    axes[0].set_xlabel("N")
    axes[0].set_ylabel("Running average")
    axes[0].legend()

    # Invariant measure
    df = pd.read_csv(measure_path, header=None, names=["bin", "freq"])
    axes[1].bar(df["bin"], df["freq"], width=1, alpha=0.6, label="Empirical")
    axes[1].set_title(f"Invariant Measure ({map_name})")
    axes[1].set_xlabel("Bin")
    axes[1].set_ylabel("Frequency")
    axes[1].legend()

    plt.tight_layout()
    out_path = os.path.join(map_dir, "ergodic_plots.png")
    plt.savefig(out_path, dpi=150)
    plt.close()
    print(f"Saved to {out_path}")